openapi: 3.0.0
info:
  title: dgoval backoffice
  version: 1.0.0
  description: ''
servers:
  - url: '{{DGOVAL_BASE_URL}}'
paths:
  /api/backoffice/auth/signup:
    post:
      summary: signup
      responses: {}
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
            example:
              firstName: Caracolas
              lastName: Store
              email: caracolasstore@gmail.com
              password: John@weq112
  /api/backoffice/auth/signin:
    post:
      summary: sign in
      responses: {}
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
            example:
              email: caracolasstore@gmail.com
              password: Password@weq112
  /api/backoffice/auth/forgot-password:
    post:
      summary: forgot-password
      responses: {}
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
            example:
              email: caracolasstore@gmail.com
  /api/backoffice/auth/reset-password:
    post:
      summary: reset-password
      responses: {}
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                newPassword:
                  type: string
            example:
              email: caracolasstore@gmail.com
              newPassword: Password@weq112
  /api/backoffice/auth/verify-reset-password:
    post:
      summary: verify-reset-password
      responses: {}
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  format: color
                email:
                  type: string
                  format: email
            example:
              otp: '959102'
              email: caracolasstore@gmail.com
  /api/backoffice/dashboard:
    get:
      summary: Get Dashboard
      responses: {}
      tags:
        - Dashboard
      security:
        - BearerAuth: []
  /api/backoffice/dashboard/metrics:
    get:
      summary: Dashboard metrics
      responses: {}
      tags:
        - Dashboard
      security:
        - BearerAuth: []
  /api/backoffice/dashboard/recent-evaluations:
    get:
      summary: Dashboard Recent evaluations
      responses: {}
      tags:
        - Dashboard
      security:
        - BearerAuth: []
  /api/backoffice/dashboard/recent-clients:
    get:
      summary: Dashboard Recent clients
      responses: {}
      tags:
        - Dashboard
      security:
        - BearerAuth: []
  /api/backoffice/users:
    get:
      summary: List backoffice users
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
          example: '10'
        - name: page
          in: query
          schema:
            type: integer
          example: '1'
        - name: search
          in: query
          schema:
            type: string
          example: caracolas
        - name: role
          in: query
          schema:
            type: string
          example: admin
        - name: status
          in: query
          schema:
            type: string
          example: active
      responses: {}
      tags:
        - User management
      security:
        - BearerAuth: []
    post:
      summary: Invite user client manager
      responses: {}
      tags:
        - User management
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
                role:
                  type: string
                backofficeLoginUrl:
                  type: string
                  format: uri
            example:
              firstName: Chidi
              lastName: Bede
              email: caracolasstore+15@gmail.com
              role: client_manager
              backofficeLoginUrl: https://app.dgoval.com/login
  /api/backoffice/auth/accept-invite:
    post:
      summary: Accept invite
      responses: {}
      tags:
        - User management
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                newPassword:
                  type: string
            example:
              token: 01KK4WG1H9SYE0NQSB1M232SMX01KK4WG1H9SYE0NQSB1M232SMY
              newPassword: John@weq112
  /api/backoffice/users/{backofficeUserId}/role:
    patch:
      summary: Update role
      responses: {}
      tags:
        - User management
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
            example:
              role: admin
    parameters:
      - name: backofficeUserId
        in: path
        required: true
        schema:
          type: string
        example: '{{backofficeUserId}}'
  /api/backoffice/users/{backofficeUserId}/deactivate:
    post:
      summary: Deactivate user
      responses: {}
      tags:
        - User management
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
            example:
              role: admin
    parameters:
      - name: backofficeUserId
        in: path
        required: true
        schema:
          type: string
        example: '{{backofficeUserId}}'
  /api/backoffice/users/{backofficeUserId}/reactivate:
    post:
      summary: Reactivate user
      responses: {}
      tags:
        - User management
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  type: string
            example:
              role: admin
    parameters:
      - name: backofficeUserId
        in: path
        required: true
        schema:
          type: string
        example: '{{backofficeUserId}}'
  /api/backoffice/users/{backofficeUserId}/resend-invite:
    post:
      summary: Resend invite
      responses: {}
      tags:
        - User management
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                backofficeLoginUrl:
                  type: string
                  format: uri
            example:
              backofficeLoginUrl: https://app.dgoval.com/login
    parameters:
      - name: backofficeUserId
        in: path
        required: true
        schema:
          type: string
        example: '{{backofficeUserId}}'
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
